
#theme: jekyll-theme-cayman
theme: jekyll-theme-dinky
page.title: "Humans in the Loop - Bringing AI & HCI Together"
description: "Interact 2019, Tuesday, 3 September 2019, Paphos, Cyprus"
markdown: kramdown
