is_project_page: false 
theme: jekyll-theme-dinky
title: "Humans in the Loop-Bringing AI and HCI Together"
description: "Interact 2019 Workshop, Tuesday 3 September 2019, Paphos, Cyprus"
markdown: kramdown
