theme: jekyll-theme-slate
title: "The Human(s) in the Loop- Bringing AI and HCI Together"
description: "Interact 2019 Workshop, Tuesday 3 September 2019, Paphos, Cyprus"
is_project_page: false
markdown: kramdown
