
theme: jekyll-theme-slate
title: "Humans in the Loop-Bringing AI & HCI Together"
description: Interact 2019, https://interact2019.org/ 
description: "Workshop, Tuesday, 3 September 2019, Paphos, Cyprus"
is_project_page: false 
markdown: kramdown
is_project_page: false 
