
theme: jekyll-theme-slate
title: "Humans in the Loop--Bringing AI & HCI Together"
description: "Interact 2019 Workshop, Tuesday, 3 September 2019, Paphos, Cyprus"
markdown: kramdown
is_project_page: false 
